### ISSUE TITLE
Any way to reset the connection?

### ISSUE THREAD

**Issue by teetow** [RomeoDespres/reapy#35] opened 2019-10-02 08:00 UTC
I'm writing an external tool that occasionally polls Reaper about its active project tab, whether it's rendering, stuff like that.

It seems whenever Reaper throws an error box, the reapy "host" gets stuck in a state where my running code throws `ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host` and I have to restart the tool. Given that the tool is designed to be fire-and-forget, I'd like to avoid this.

Any pointers? Any way of reinitializing reapy without restarting my tool?

**Comment by RomeoDespres** [comment] 2019-10-02 08:19
Could you give me an example of such an error box that generates this state?

**Comment by teetow** [comment] 2019-10-02 09:21
The most reliable way is to try and switch projects.

```
Deferred script execution error

Traceback (most recent call last):
  File "defer", line 1, in <module>
  File "C:\...\Python37\lib\site-packages\reapy\core\reaper\defer.py", line 48, in run
    callback(*args, **kwargs)
  File "activate_reapy_server.py", line 24, in run_main_loop
    SERVER.send_results(results)
  File "C:\...\Python37\lib\site-packages\reapy\tools\network\server.py", line 111, in send_results
    self._send_result(connection, result)
  File "C:\...\Python37\lib\site-packages\reapy\tools\network\server.py", line 77, in _send_result
    result = json.dumps(result).encode()
  File "C:\...\Python37\lib\site-packages\reapy\tools\json.py", line 46, in dumps
    return json.dumps(x, cls=ReapyEncoder)
  File "c:\...\Python37\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\...\Python37\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\...\Python37\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\...\Python37\lib\site-packages\reapy\tools\json.py", line 38, in default
    return json.JSONEncoder.default(self, x)
  File "c:\...\Python37\Lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _MakeCurrentProject is not JSON serializable
```

**Comment by RomeoDespres** [comment] 2019-10-02 09:40
Ok, this looks like it's a bug inside reapy. I mean normally you don't have errors, so you don't have to reset it. I'll try to fix that soon!

**Comment by teetow** [comment] 2019-10-02 09:52
Right, however I tried to use `reapy.reascript_api.SelectProjectInstance()`, and I can still get issues (just not as reliably). Additionally, terminating my tool at just the wrong moment also seems to cause Reaper to throw an error message. I hope you can find some time and investigate exactly how that situation could be dealt with.

Meanwhile, I'll try and rewrite my code to avoid e.g. calling for a project tab switch while in the middle of checking the current project. I suspect Reaper might not handle that too well.

**Comment by RomeoDespres** [comment] 2019-10-02 10:01
Hm it's definitely weird if you get errors while using `SelectProjectInstance`. If it happens again I'd be very interested if you could provide me with the error message.

Similarly, if you get an error when terminating your tool, please post the error. It may help to understand where the probleme comes from.

Concerning your first post, what you were asking for was some function say `reapy.reconnect` that you would call whenever you encounter a problem? It may be an interesting feature if we don't manage to get rid of all your errors.

**Comment by teetow** [comment] 2019-10-02 11:26
Absolutely, I'll get back to you with more dumps / repro steps as I encounter them. 

> what you were asking for was some function say reapy.reconnect that you would call whenever you encounter a problem? It may be an interesting feature if we don't manage to get rid of all your errors.

I think it'd be valuable. If nothing else for extra safety in production-critical environments.

**Comment by teetow** [comment] 2019-10-04 13:27
For example, here's an error that Reaper can throw, about 1 in 20 times I terminate my script. Once the user has dismissed the error box in Reaper, the tool can start normally.

I currently have no way for my tool to wait until the user does so, since reapy will simply hang, and then throw an exception. It would be preferable for reapy to give up, throw an exception. I could then wait for the user to close the error box, then re-initialize reapy.

```
Deferred script execution error

Traceback (most recent call last):
  File "defer", line 1, in <module>
  File "C:\...\Python37\lib\site-packages\reapy\core\reaper\defer.py", line 48, in run
    callback(*args, **kwargs)
  File "activate_reapy_server.py", line 24, in run_main_loop
    SERVER.send_results(results)
  File "C:\...\Python37\lib\site-packages\reapy\tools\network\server.py", line 111, in send_results
    self._send_result(connection, result)
  File "C:\...\Python37\lib\site-packages\reapy\tools\network\server.py", line 78, in _send_result
    connection.send(result)
  File "C:\...\Python37\lib\site-packages\reapy\tools\network\socket.py", line 59, in send
    self._socket.sendall(length)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

**Comment by RomeoDespres** [comment] 2019-10-05 06:50
I don't manage to reproduce your problem at home, so it makes it uneasy to debug it. If it's ok with, I would suggest we directly try to modify reapy's source code in your computer and see if it works.

Please first locate the file `server.py`:

```python
>>> import reapy.tools.network.server
>>> print(reapy.tools.network.server.__file__)
```

Then navigate there, make a copy of `server.py` as e.g. `server_backup.py` (just to backup the original file). Then please replace line 112 of `server.py`, that contains:
```except (KeyError, BrokenPipeError):```
by:
```except (KeyError, BrokenPipeError, ConnectionAbortedError, ConnectionResetError):```

You can now restart REAPER and hopefully it will be enough to remove the last error you reported... (the first one is a `reapy` bug and will soon be fixed). Please let me know if it works!

P.S. Still, I'll work on that `reconnect` function when I get time, cause I think it's a nice idea.

**Comment by teetow** [comment] 2019-10-21 11:30
Hey, so I've been playing around a bit more with all this, and I'll just post some thoughts.

High-level, I'm trying to automate the installation and initialization of Reapy as much as possible, since my external tool depends on it for parts of its functionality. This involves some hacking; manipulating Reaper config files directly, adding the Reapy init command to `__startup.lua` and so on. 

Where I feel I have the most issues right now is that Reapy cannot be imported without also trying to connect to the Reapy server. Furthermore, it can only be done once, and that's by doing `import reapy` inside a thread and waiting for it to either succeed or freeze. Having frozen once, it cannot be re-attempted without restarting my application. 

For that purpose, it would be incredibly helpful to be able to import Reapy without side effects, call something like `reapy.canConnect()` safely and *then* do `reapy.initialize()` or something similar if `canConnect()` returns True.

Secondly, anything you can do / explain to make the Reapy installation process as hassle-free as possible for third parties would be a great bonus, like a `reapy.installScripts()` that can be called from the outside, or a `reapy.activateServer()` that can be run from the aforementioned `__startup.lua` (again, without side effects if something fails) to facilitate bootstrapping Reapy without user interaction. Again, just keeping this high-level, but anything that cuts down on the hacks I mentioned above would be very welcome.

Thanks again for an invaluable tool!

**Comment by RomeoDespres** [comment] 2019-10-27 09:54
My feeling is that reapy has to try to connect on first import, because for most use cases, it would be super annoying to have to write
```python
import reapy
if reapy.can_connect:
    reapy.connect()
```
at the top of every script using reapy. Would it work for you if reapy provided a `reconnect` function, while still attempting to connect automatically at first import?

Regarding your questions about installation: I don't know Lua and the way it integrates with REAPER at all. I feel `reapy` installation process is already quite simple: one `pip install` and one manual configuration step. If you find any way to remove this manual step, maybe by integrating it into a Lua script, it would be amazing and I'd be glad to integrate it into the project! But I don't think I would know how to do that myself...

**Comment by teetow** [comment] 2019-10-27 18:25
Oh, absolutely. I'd probably want to use it like this:

```
import reapy  # no side-effects if it fails

def main():
    while not reapy.can_connect():
        # notify user
        time.sleep(10)
        reapy.reconnect(timeout=3)
    do_reapy_stuff()
```

Just from memory, here's how I did the install (will edit with accurate info later)

* Do some black magic $%^&ery to get Reaper to run redistributable Python builds. Can give you details on this somewhere else if you're interested, I'm available at my user name @ gmail.
* Hack `reaper.ini` to set up a web interface, kinda what your installer does.
* Hack `reaper-kb.ini` to add the custom action (again, this is just replicating what your installer does)
* Add a tiny `__startup.lua` script (Reaper looks for and runs it on every launch) that checks for the `server_port` ext_state that Reapy sets. If no such state is found, trigger the Reapy installer action we hacked into `reaper_kb.ini` earlier.

On that note, it would be kinda neat if there was something else I could import rather than just `reapy`, let's call it `reapy.setup,` that contains all the things you do during the user-initialized installation. It would make me duplicate way less code, and we could put all the connection checkers etc in there. I'd imagine the API would look something like:

* `reapy.setup.add_web_port()` (and of course the `remove` function aswell)
* `reapy.setup.add_custom_action()`
* `reapy.setup.verify()`

**Comment by RomeoDespres** [comment] 2019-10-30 11:34
Ok thanks! I'll try to work on it this weekend!

**Comment by RomeoDespres** [comment] 2019-11-03 09:29
Hello again, 
the `reconnect` function has been added to the `master` and will be released as soon as we fix all other points in this issue. Regarding those:
- There already is a `can_connect` function that is actually called `reapy.dist_api_is_enabled()`.
- There already is a module `reapy.config` that contains `create_new_web_interface(port)` and `delete_web_interface(port)`.
- There also are functions `reapy.add_reascript` and `reapy.remove_reascript`. However, these currently use the ReaScript function `RPR_AddRemoveReaScript`, which means they can not be used from the outside before `reapy` has been installed... This is actually the only thing that prevents a full automatic setup process. Hence I would be super interested in knowing how you manually hack into `reaper-kb.ini` (I didn't know this file existed before!). More specifically, how do you generate the codes for ReaScripts (you know these `RS1ee9bb229dabffe151848d7efa3c10f748e1a1cf `)? Do you just use any random value?

Oh and also,  you have been mentioning several times that `reapy` has side effects when imported, but I don't think it does, does it? It simply tries to connect, and raises a warning if it fails.

**Comment by teetow** [comment] 2019-11-03 10:32
> the `reconnect` function has been added to the `master` and will be released as soon as we fix all other points in this issue. Regarding those:
> 
> * There already is a `can_connect` function that is actually called `reapy.dist_api_is_enabled()`.
> * There already is a module `reapy.config` that contains `create_new_web_interface(port)` and `delete_web_interface(port)`.

Yeah, I only just discovered those. That will help a lot!

> I would be super interested in knowing how you manually hack into `reaper-kb.ini` (I didn't know this file existed before!). More specifically, how do you generate the codes for ReaScripts (you know these `RS1ee9bb229dabffe151848d7efa3c10f748e1a1cf `)? Do you just use any random value?

I do, yeah. To cut down on roundtrips between my python code and the code in `__startup.lua` that would otherwise be responsible for creating the command and somehow communicating the actionId back to my Python code. I deemed it safe enough for my purposes.

> Oh and also, you have been mentioning several times that `reapy` has side effects when imported, but I don't think it does, does it? It simply tries to connect, and raises a warning if it fails.

I think I have to go back to the code to verify all this, but essentially I can only `import reapy` once in a project. If it fails, I can never import it again for the lifetime of the session. I also have several instances of `import reapy` freezing up the tool, and requiring me to restart it; I think it's when Reaper is showing an error dialog. You mentioned above that reapy catching more types of exceptions might prevent this, and I think it's a good idea. 

Again; for my purposes, `import reapy` isn't necessarily the point at which I need to make a connection. A failure to connect is not relevant until I need to ask something from Reaper, at which point the try - fail - reconnect pattern I described above would kick in. The `reconnect()` function is perfect for that!

**Comment by RomeoDespres** [comment] 2019-11-03 16:46
Thanks! There is still something I don't understand.

If I'm not mistaken, you hack into `reaper.ini` and `reaper-kb.ini` during the installation process of your tool. Is this installer a Python program? And do you run it from inside or outside REAPER? If from inside REAPER, then you can directly use `reapy.config.enable_dist_api()` to avoid those two hacks. If from outside REAPER, then how do you locate the two files? That's actually the only blocking point to make the whole installation of `reapy` doable from outside REAPER. Using `RPR_get_ini_file()` (only available from inside REAPER as long as reapy distant API hasn't been enabled) is the only way I've found to do it so far.

**Comment by teetow** [comment] 2019-11-03 22:57
> If I'm not mistaken, you hack into `reaper.ini` and `reaper-kb.ini` during the installation process of your tool. Is this installer a Python program? 

Yup.

> And do you run it from inside or outside REAPER? If from inside REAPER, then you can directly use `reapy.config.enable_dist_api()` to avoid those two hacks. If from outside REAPER, then how do you locate the two files? 

It's run from outside Reaper, and I just assume them to be in `~/AppData/Roaming/REAPER/` since I don't recall that being something user configurable. My users are all on Windows, but I hope it'd be doable to figure out the corresponding folders on other platforms.

**Comment by RomeoDespres** [comment] 2019-11-23 16:49
Hey! You can now upgrade reapy and have the `reapy.reconnect()` function... Sorry about the delay! I'm also trying to make the whole installation automatic from outside REAPER, with a post-pip install hook, but this is probably gonna take some more time...

**Comment by teetow** [comment] 2019-11-24 22:41
Fantastic! Yeah, I switched to running from the github repo recently, the new functionality definitely helped stabilize the connection.

Good luck with the installer, don't forget that someone in my position will wanna run that installer on my client machines (meaning from something like `reapy.config`), not just in my dev environment =)

Thanks for the great support!

**Comment by RomeoDespres** [comment] 2020-03-18 11:22
I'll close this one now that #61 deals with command-line installation.

**Closed by RomeoDespres** 2020-03-18 11:22 UTC
